// ===== TRANSLATIONS =====
const translations = {
  en: {
    // Announcement bar
    annLink1: "FIND A STORE",
    annLink2: "VIEW OUR PRODUCTS!",
    // Info bar
    shippingInfo: "Free shipping – Order before 18:00, delivered within 2 days",
    searchPlaceholder: "Search products...",
    // Nav
    navProducts: "PRODUCTS",
    navLocations: "VISIT A STORE",
    navAbout: "ABOUT US",
    // Hero
    heroTag: "DEALS OF THE WEEK",
    heroTitle: "FITTER WITH <span>PERSONAL</span> ADVICE",
    heroPanelTitle: "€1,- DEALS",
    heroPanelText: "Take advantage of our sharpest offers",
    heroCta: "VIEW PRODUCTS",
    // Best sellers
    bestSellerSub: "Popular",
    bestSellerTitle: "BEST SELLER",
    viewMore: "VIEW ALL PRODUCTS",
    comingSoon: "Coming Soon",
    // Newsletter
    nlSub: "Stay updated",
    nlTitle: "10% OFF YOUR FIRST ORDER",
    nlText: "Join The Health House Thailand for exclusive access to our launches, the latest products + nutrition and fitness advice from our experts.",
    nlPlaceholder: "Your e-mail address",
    nlBtn: "SUBSCRIBE",
    // About Us (index page teaser)
    aboutSub: "Our Story",
    aboutTitle: "THE NETHERLANDS' #1 SPORTS NUTRITION STORE IS COMING TO THAILAND",
    aboutP1: "The Health House started in 2019 as a small sports nutrition store in the Netherlands. With a passion for health, fitness and personal advice, we quickly grew into the largest sports nutrition chain in the country — with over 20 stores, 100+ employees, and thousands of happy customers.",
    aboutP2: "Our mission has always been the same: making premium supplements, vitamins and healthy products accessible to everyone — with expert advice you can trust. Whether you're a professional athlete, a gym enthusiast, or simply looking to live healthier.",
    aboutP3: "Now, we're bringing The Health House to Thailand. Same quality, same personal service, same passion — in the heart of Southeast Asia. Our stores in Thailand will carry the best European and international brands, combined with local expertise and a team that truly cares about your goals.",
    aboutP4: "Welcome to The Health House Thailand. Your health journey starts here. 🇹🇭",
    aboutReadMore: "READ OUR FULL STORY",
    aboutStat1: "Stores in the Netherlands",
    aboutStat2: "Employees",
    aboutStat3: "Premium Brands",
    aboutStat4: "Sports Nutrition Chain in NL",
    // About page
    aboutHeroSub: "OUR MISSION",
    aboutHeroTitle: "MOTIVATE & SUPPORT YOUR DESIRE TO LIVE WELL",
    aboutHeroDesc: "From a small store in the Netherlands to Southeast Asia — The Health House is dedicated to making premium health products and expert advice accessible to everyone.",
    aboutPromiseSub: "Our Promise",
    aboutPromiseTitle: "WHAT MAKES THE HEALTH HOUSE SPECIAL",
    aboutPromiseP1: "At The Health House, we believe that everyone deserves access to premium quality supplements, vitamins, and healthy products — combined with expert advice you can truly trust.",
    aboutPromiseP2: "Unlike other supplement stores, we don't just sell products. Our trained staff takes the time to understand your goals, your lifestyle, and your body — so we can recommend exactly what works for you.",
    aboutPromiseP3: "That personal touch is what made us the #1 sports nutrition chain in the Netherlands. And now, we're bringing that same experience to Thailand.",
    pillarQualityTitle: "Quality Products",
    pillarQualityText: "We carry only the highest-quality European and international brands. Every product in our store meets strict quality standards — because your health deserves nothing less.",
    pillarAdviceTitle: "Personal Advice",
    pillarAdviceText: "Our expert staff provides tailored recommendations based on your individual goals. Whether you're a beginner or a pro athlete, we'll help you find exactly what you need.",
    pillarGlobalTitle: "Global Reach",
    pillarGlobalText: "From a single store in the Netherlands to Southeast Asia — we're on a mission to make premium health products accessible worldwide. Thailand is our next chapter.",
    aboutStorySub: "Our Story",
    aboutStoryTitle: "FROM A CORNER STORE TO A POWERHOUSE",
    timeline2019Title: "The Beginning",
    timeline2019Text: "The Health House opens its first store in the Netherlands — a small sports nutrition shop with a big vision: make premium supplements accessible with personal, expert advice.",
    timeline2020Title: "Rapid Growth",
    timeline2020Text: "Despite the pandemic, word spreads fast. Customers love our personal approach. We expand to multiple locations across the Netherlands and launch our online store.",
    timeline2022Title: "Market Leader",
    timeline2022Text: "The Health House becomes the Netherlands' #1 sports nutrition chain with 20+ stores, 100+ employees, and partnerships with top European brands.",
    timeline2025Title: "International Expansion",
    timeline2025Text: "We set our sights on Southeast Asia. Thailand is chosen as our first international market — with Bangkok, Chiang Mai, and Phuket as launch cities.",
    timeline2026Title: "Thailand Launch",
    timeline2026Text: "The Health House Thailand opens its doors. The same quality, the same personal service, the same passion — now in the heart of Southeast Asia. 🇹🇭",
    aboutQuoteText: "\"We started The Health House because we believed everyone deserves access to quality products and honest advice. That mission hasn't changed — it's just gotten bigger. Thailand, we're excited to meet you.\"",
    aboutQuoteCite: "— The Health House Founders",
    // Products page
    productsBannerTitle: "🚀 COMING SOON TO THAILAND",
    productsBannerText: "We're bringing the best European sports nutrition & health brands to Thailand. Browse our full catalog below — all products will be available in our Thai stores soon!",
    productsCatalogSub: "Our Catalog",
    productsCatalogTitle: "ALL PRODUCTS",
    productsCount: "products",
    productsNote: "All products shown are from our Netherlands catalog and will be available in Thailand stores soon. Prices may vary.",
    filterAll: "All",
    // Pre-footer CTA
    prefooterVisitTitle: "Visit Our Store",
    prefooterVisitText: "Get personal advice from our nutrition experts in-store",
    prefooterVisitBtn: "FIND A STORE",
    prefooterShopTitle: "Shop Online",
    prefooterShopText: "Browse our full product range and order from anywhere in Thailand",
    prefooterShopBtn: "BROWSE PRODUCTS",
    // Footer
    footerColTitle: "The Health House",
    footerShop: "Products",
    footerBrands: "Brands",
    footerAbout: "About Us",
    footerFranchise: "Franchise",
    footerServiceTitle: "Customer Service",
    footerContact: "Contact",
    footerJobs: "Careers",
    footerFAQ: "FAQ",
    footerReturns: "Returns & Refunds",
    footerShipping: "Shipping Info",
    footerLocTitle: "Our Locations",
    footerLoc1: "Bangkok Sukhumvit",
    footerLoc2: "Bangkok Thonglor",
    footerLoc3: "Chiang Mai",
    footerLoc4: "Phuket",
    footerNewsletterTitle: "STAY CONNECTED",
    footerNewsletterText: "Get the latest deals, new arrivals and exclusive offers when you sign up",
    footerNewsletterPlaceholder: "Enter email",
    footerNewsletterBtn: "SIGN UP",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms & Conditions",
    footerCookies: "Cookies",
  },

  nl: {
    annLink1: "ZOEK EEN WINKEL",
    annLink2: "BEKIJK ONZE PRODUCTEN!",
    shippingInfo: "Gratis verzending – Voor 18:00 besteld, binnen 2 dagen in huis",
    searchPlaceholder: "Zoeken naar producten...",
    navProducts: "ONLINE BESTELLEN",
    navLocations: "BEZOEK EEN WINKEL",
    navAbout: "OVER ONS",
    heroTag: "DEALS VAN DE WEEK",
    heroTitle: "FITTER MET <span>PERSOONLIJK</span> ADVIES",
    heroPanelTitle: "€1,- DEALS",
    heroPanelText: "Profiteer van onze scherpste aanbiedingen",
    heroCta: "BEKIJK DE PRODUCTEN",
    bestSellerSub: "Populair",
    bestSellerTitle: "BEST SELLER",
    viewMore: "BEKIJK MEER PRODUCTEN",
    comingSoon: "Binnenkort beschikbaar",
    nlSub: "Blijf op de hoogte",
    nlTitle: "10% KORTING OP JE EERSTE BESTELLING",
    nlText: "Word lid van The Health House Thailand en krijg exclusieve toegang tot onze lanceringen, de nieuwste producten + voedings- en fitnessadvies van onze experts.",
    nlPlaceholder: "Je e-mailadres",
    nlBtn: "AANMELDEN",
    aboutSub: "Ons Verhaal",
    aboutTitle: "DE GROOTSTE SPORTVOEDINGSWINKEL VAN NEDERLAND KOMT NAAR THAILAND",
    aboutP1: "The Health House begon in 2019 als een kleine sportvoedingswinkel in Nederland. Met een passie voor gezondheid, fitness en persoonlijk advies groeiden we al snel uit tot de grootste sportvoedingsketen van het land — met meer dan 20 winkels, 100+ medewerkers en duizenden tevreden klanten.",
    aboutP2: "Onze missie is altijd hetzelfde geweest: premium supplementen, vitamines en gezonde producten toegankelijk maken voor iedereen — met deskundig advies waar je op kunt vertrouwen. Of je nu topsporter bent, een fanatieke gymsporter, of gewoon gezonder wilt leven.",
    aboutP3: "Nu brengen we The Health House naar Thailand. Dezelfde kwaliteit, dezelfde persoonlijke service, dezelfde passie — in het hart van Zuidoost-Azië. Onze winkels in Thailand bieden de beste Europese en internationale merken, gecombineerd met lokale expertise en een team dat écht geeft om jouw doelen.",
    aboutP4: "Welkom bij The Health House Thailand. Jouw gezondheidsreis begint hier. 🇹🇭",
    aboutReadMore: "LEES ONS VOLLEDIGE VERHAAL",
    aboutStat1: "Winkels in Nederland",
    aboutStat2: "Medewerkers",
    aboutStat3: "Premium Merken",
    aboutStat4: "Sportvoedingsketen in NL",
    // About page
    aboutHeroSub: "ONZE MISSIE",
    aboutHeroTitle: "MOTIVEER & ONDERSTEUN JOUW VERLANGEN OM GOED TE LEVEN",
    aboutHeroDesc: "Van een kleine winkel in Nederland tot Zuidoost-Azië — The Health House zet zich in om premium gezondheidsproducten en deskundig advies voor iedereen toegankelijk te maken.",
    aboutPromiseSub: "Onze Belofte",
    aboutPromiseTitle: "WAT THE HEALTH HOUSE BIJZONDER MAAKT",
    aboutPromiseP1: "Bij The Health House geloven we dat iedereen toegang verdient tot premium supplementen, vitamines en gezonde producten — gecombineerd met deskundig advies waar je echt op kunt vertrouwen.",
    aboutPromiseP2: "In tegenstelling tot andere supplementenwinkels, verkopen wij niet alleen producten. Ons getrainde personeel neemt de tijd om jouw doelen, levensstijl en lichaam te begrijpen — zodat we precies kunnen aanbevelen wat voor jou werkt.",
    aboutPromiseP3: "Die persoonlijke touch maakte ons de #1 sportvoedingsketen in Nederland. En nu brengen we diezelfde ervaring naar Thailand.",
    pillarQualityTitle: "Kwaliteitsproducten",
    pillarQualityText: "Wij verkopen alleen de hoogste kwaliteit Europese en internationale merken. Elk product in onze winkel voldoet aan strenge kwaliteitsnormen — want jouw gezondheid verdient niets minder.",
    pillarAdviceTitle: "Persoonlijk Advies",
    pillarAdviceText: "Ons deskundig personeel biedt op maat gemaakte aanbevelingen op basis van jouw individuele doelen. Of je nu een beginner bent of een professionele atleet, wij helpen je precies te vinden wat je nodig hebt.",
    pillarGlobalTitle: "Wereldwijd Bereik",
    pillarGlobalText: "Van een enkele winkel in Nederland tot Zuidoost-Azië — we zijn op een missie om premium gezondheidsproducten wereldwijd toegankelijk te maken. Thailand is ons volgende hoofdstuk.",
    aboutStorySub: "Ons Verhaal",
    aboutStoryTitle: "VAN EEN KLEINE WINKEL TOT EEN GROOTMACHT",
    timeline2019Title: "Het Begin",
    timeline2019Text: "The Health House opent zijn eerste winkel in Nederland — een kleine sportvoedingswinkel met een grote visie: premium supplementen toegankelijk maken met persoonlijk, deskundig advies.",
    timeline2020Title: "Snelle Groei",
    timeline2020Text: "Ondanks de pandemie verspreidt het nieuws zich snel. Klanten zijn dol op onze persoonlijke aanpak. We breiden uit naar meerdere locaties in Nederland en lanceren onze webshop.",
    timeline2022Title: "Marktleider",
    timeline2022Text: "The Health House wordt de #1 sportvoedingsketen van Nederland met 20+ winkels, 100+ medewerkers en partnerschappen met top Europese merken.",
    timeline2025Title: "Internationale Expansie",
    timeline2025Text: "We richten onze blik op Zuidoost-Azië. Thailand wordt gekozen als onze eerste internationale markt — met Bangkok, Chiang Mai en Phuket als lanceersteden.",
    timeline2026Title: "Thailand Launch",
    timeline2026Text: "The Health House Thailand opent haar deuren. Dezelfde kwaliteit, dezelfde persoonlijke service, dezelfde passie — nu in het hart van Zuidoost-Azië. 🇹🇭",
    aboutQuoteText: "\"We zijn begonnen met The Health House omdat we geloofden dat iedereen toegang verdient tot kwaliteitsproducten en eerlijk advies. Die missie is niet veranderd — hij is alleen groter geworden. Thailand, we kijken ernaar uit jullie te ontmoeten.\"",
    aboutQuoteCite: "— De Oprichters van The Health House",
    // Products page
    productsBannerTitle: "🚀 BINNENKORT IN THAILAND",
    productsBannerText: "We brengen de beste Europese sportvoeding & gezondheidsmerken naar Thailand. Bekijk hieronder onze volledige catalogus — alle producten zullen binnenkort beschikbaar zijn in onze Thaise winkels!",
    productsCatalogSub: "Ons Aanbod",
    productsCatalogTitle: "ALLE PRODUCTEN",
    productsCount: "producten",
    productsNote: "Alle getoonde producten komen uit onze Nederlandse catalogus en zullen binnenkort beschikbaar zijn in Thailand. Prijzen kunnen afwijken.",
    filterAll: "Alles",
    // Pre-footer CTA
    prefooterVisitTitle: "Bezoek onze winkel",
    prefooterVisitText: "Krijg persoonlijk advies van onze voedingsexperts in de winkel",
    prefooterVisitBtn: "ZOEK EEN WINKEL",
    prefooterShopTitle: "Shop online",
    prefooterShopText: "Bekijk ons volledige productaanbod en bestel vanuit heel Thailand",
    prefooterShopBtn: "BEKIJK PRODUCTEN",
    // Footer
    footerColTitle: "The Health House",
    footerShop: "Producten",
    footerBrands: "Merken",
    footerAbout: "Over ons",
    footerFranchise: "Franchise",
    footerServiceTitle: "Klantenservice",
    footerContact: "Contact",
    footerJobs: "Werken bij",
    footerFAQ: "Veelgestelde vragen",
    footerReturns: "Retourneren",
    footerShipping: "Verzendinfo",
    footerLocTitle: "Onze locaties",
    footerLoc1: "Bangkok Sukhumvit",
    footerLoc2: "Bangkok Thonglor",
    footerLoc3: "Chiang Mai",
    footerLoc4: "Phuket",
    footerNewsletterTitle: "BLIJF OP DE HOOGTE",
    footerNewsletterText: "Ontvang de laatste deals, nieuwe producten en exclusieve aanbiedingen",
    footerNewsletterPlaceholder: "E-mailadres",
    footerNewsletterBtn: "AANMELDEN",
    footerPrivacy: "Privacy beleid",
    footerTerms: "Algemene voorwaarden",
    footerCookies: "Cookies",
  },

  th: {
    annLink1: "ค้นหาร้าน",
    annLink2: "ดูสินค้าทั้งหมด!",
    shippingInfo: "จัดส่งฟรี – สั่งก่อน 18:00 จัดส่งภายใน 2 วัน",
    searchPlaceholder: "ค้นหาสินค้า...",
    navProducts: "สั่งซื้อออนไลน์",
    navLocations: "เยี่ยมชมร้าน",
    navAbout: "เกี่ยวกับเรา",
    heroTag: "ดีลประจำสัปดาห์",
    heroTitle: "ฟิตขึ้นด้วย <span>คำแนะนำ</span> ส่วนตัว",
    heroPanelTitle: "โปรโมชั่น ฿1",
    heroPanelText: "ใช้ประโยชน์จากข้อเสนอที่ดีที่สุดของเรา",
    heroCta: "ดูสินค้า",
    bestSellerSub: "ยอดนิยม",
    bestSellerTitle: "สินค้าขายดี",
    viewMore: "ดูสินค้าทั้งหมด",
    comingSoon: "เร็วๆ นี้",
    nlSub: "ติดตามข่าวสาร",
    nlTitle: "ลด 10% สำหรับออร์เดอร์แรก",
    nlText: "เข้าร่วม The Health House Thailand เพื่อรับสิทธิ์พิเศษก่อนใคร รับข่าวสารผลิตภัณฑ์ล่าสุด + คำแนะนำด้านโภชนาการและฟิตเนสจากผู้เชี่ยวชาญ",
    nlPlaceholder: "อีเมลของคุณ",
    nlBtn: "สมัครรับข่าวสาร",
    aboutSub: "เรื่องราวของเรา",
    aboutTitle: "ร้านอาหารเสริมกีฬาอันดับ 1 ของเนเธอร์แลนด์ มาถึงประเทศไทยแล้ว",
    aboutP1: "The Health House เริ่มต้นในปี 2019 เป็นร้านอาหารเสริมกีฬาเล็กๆ ในเนเธอร์แลนด์ ด้วยความหลงใหลในสุขภาพ ฟิตเนส และคำแนะนำส่วนบุคคล เราเติบโตอย่างรวดเร็วจนกลายเป็นเครือข่ายร้านอาหารเสริมกีฬาที่ใหญ่ที่สุดในประเทศ — ด้วยร้านค้ามากกว่า 20 สาขา พนักงาน 100+ คน และลูกค้าหลายพันคนที่มีความสุข",
    aboutP2: "ภารกิจของเราเหมือนเดิมเสมอ: ทำให้อาหารเสริมพรีเมียม วิตามิน และผลิตภัณฑ์เพื่อสุขภาพเข้าถึงได้สำหรับทุกคน — พร้อมคำแนะนำจากผู้เชี่ยวชาญที่คุณวางใจได้ ไม่ว่าคุณจะเป็นนักกีฬามืออาชีพ คนรักการออกกำลังกาย หรือเพียงแค่ต้องการใช้ชีวิตที่สุขภาพดีขึ้น",
    aboutP3: "ตอนนี้ เรากำลังนำ The Health House มาสู่ประเทศไทย คุณภาพเดียวกัน บริการส่วนตัวเหมือนเดิม ความหลงใหลเดียวกัน — ใจกลางเอเชียตะวันออกเฉียงใต้ ร้านค้าของเราในประเทศไทยจะมีแบรนด์ยุโรปและนานาชาติที่ดีที่สุด ผสมผสานกับความเชี่ยวชาญในท้องถิ่นและทีมงานที่ใส่ใจเป้าหมายของคุณอย่างแท้จริง",
    aboutP4: "ยินดีต้อนรับสู่ The Health House Thailand การเดินทางสู่สุขภาพที่ดีของคุณเริ่มต้นที่นี่ 🇹🇭",
    aboutReadMore: "อ่านเรื่องราวทั้งหมดของเรา",
    aboutStat1: "สาขาในเนเธอร์แลนด์",
    aboutStat2: "พนักงาน",
    aboutStat3: "แบรนด์พรีเมียม",
    aboutStat4: "เครือข่ายอาหารเสริมกีฬาอันดับ 1 ใน NL",
    // About page
    aboutHeroSub: "ภารกิจของเรา",
    aboutHeroTitle: "สร้างแรงบันดาลใจและสนับสนุนความปรารถนาที่จะมีสุขภาพดี",
    aboutHeroDesc: "จากร้านเล็กๆ ในเนเธอร์แลนด์สู่เอเชียตะวันออกเฉียงใต้ — The Health House มุ่งมั่นที่จะทำให้ผลิตภัณฑ์สุขภาพพรีเมียมและคำแนะนำจากผู้เชี่ยวชาญเข้าถึงได้สำหรับทุกคน",
    aboutPromiseSub: "คำมั่นสัญญาของเรา",
    aboutPromiseTitle: "อะไรทำให้ THE HEALTH HOUSE พิเศษ",
    aboutPromiseP1: "ที่ The Health House เราเชื่อว่าทุกคนสมควรได้รับสิทธิ์เข้าถึงอาหารเสริม วิตามิน และผลิตภัณฑ์เพื่อสุขภาพคุณภาพพรีเมียม — ผสมผสานกับคำแนะนำจากผู้เชี่ยวชาญที่คุณวางใจได้อย่างแท้จริง",
    aboutPromiseP2: "ต่างจากร้านอาหารเสริมอื่นๆ เราไม่ได้แค่ขายสินค้า พนักงานที่ผ่านการฝึกอบรมของเราใช้เวลาเพื่อเข้าใจเป้าหมาย ไลฟ์สไตล์ และร่างกายของคุณ — เพื่อแนะนำสิ่งที่เหมาะกับคุณอย่างแม่นยำ",
    aboutPromiseP3: "สัมผัสส่วนตัวนี้ทำให้เราเป็นเครือข่ายอาหารเสริมกีฬาอันดับ 1 ในเนเธอร์แลนด์ และตอนนี้ เรากำลังนำประสบการณ์เดียวกันมาสู่ประเทศไทย",
    pillarQualityTitle: "สินค้าคุณภาพ",
    pillarQualityText: "เราจำหน่ายเฉพาะแบรนด์ยุโรปและนานาชาติคุณภาพสูงสุดเท่านั้น ทุกผลิตภัณฑ์ในร้านของเราผ่านมาตรฐานคุณภาพที่เข้มงวด — เพราะสุขภาพของคุณสมควรได้รับสิ่งที่ดีที่สุด",
    pillarAdviceTitle: "คำแนะนำส่วนบุคคล",
    pillarAdviceText: "พนักงานผู้เชี่ยวชาญของเราให้คำแนะนำที่ปรับให้เหมาะกับเป้าหมายของคุณ ไม่ว่าคุณจะเป็นมือใหม่หรือนักกีฬามืออาชีพ เราจะช่วยคุณหาสิ่งที่คุณต้องการ",
    pillarGlobalTitle: "เข้าถึงทั่วโลก",
    pillarGlobalText: "จากร้านเดียวในเนเธอร์แลนด์สู่เอเชียตะวันออกเฉียงใต้ — เรามีภารกิจที่จะทำให้ผลิตภัณฑ์สุขภาพพรีเมียมเข้าถึงได้ทั่วโลก ประเทศไทยคือบทต่อไปของเรา",
    aboutStorySub: "เรื่องราวของเรา",
    aboutStoryTitle: "จากร้านเล็กๆ สู่แบรนด์ระดับโลก",
    timeline2019Title: "จุดเริ่มต้น",
    timeline2019Text: "The Health House เปิดร้านแรกในเนเธอร์แลนด์ — ร้านอาหารเสริมกีฬาเล็กๆ ที่มีวิสัยทัศน์ใหญ่: ทำให้อาหารเสริมพรีเมียมเข้าถึงได้พร้อมคำแนะนำส่วนบุคคลจากผู้เชี่ยวชาญ",
    timeline2020Title: "เติบโตอย่างรวดเร็ว",
    timeline2020Text: "แม้จะอยู่ในช่วงโรคระบาด แต่ข่าวแพร่กระจายอย่างรวดเร็ว ลูกค้าชื่นชอบแนวทางส่วนบุคคลของเรา เราขยายไปหลายสาขาทั่วเนเธอร์แลนด์และเปิดร้านออนไลน์",
    timeline2022Title: "ผู้นำตลาด",
    timeline2022Text: "The Health House กลายเป็นเครือข่ายอาหารเสริมกีฬาอันดับ 1 ของเนเธอร์แลนด์ ด้วย 20+ สาขา พนักงาน 100+ คน และพันธมิตรกับแบรนด์ชั้นนำของยุโรป",
    timeline2025Title: "ขยายสู่สากล",
    timeline2025Text: "เรามุ่งสู่เอเชียตะวันออกเฉียงใต้ ประเทศไทยถูกเลือกเป็นตลาดต่างประเทศแห่งแรก — โดยมีกรุงเทพฯ เชียงใหม่ และภูเก็ตเป็นเมืองเปิดตัว",
    timeline2026Title: "เปิดตัวในประเทศไทย",
    timeline2026Text: "The Health House Thailand เปิดประตูต้อนรับ คุณภาพเดียวกัน บริการส่วนตัวเหมือนเดิม ความหลงใหลเดียวกัน — ตอนนี้อยู่ใจกลางเอเชียตะวันออกเฉียงใต้ 🇹🇭",
    aboutQuoteText: "\"เราเริ่มต้น The Health House เพราะเราเชื่อว่าทุกคนสมควรได้รับสินค้าคุณภาพและคำแนะนำที่จริงใจ ภารกิจนั้นไม่เปลี่ยน — มันแค่ใหญ่ขึ้น ประเทศไทย เราตื่นเต้นที่จะได้พบคุณ\"",
    aboutQuoteCite: "— ผู้ก่อตั้ง The Health House",
    // Products page
    productsBannerTitle: "🚀 เร็วๆ นี้ในประเทศไทย",
    productsBannerText: "เรากำลังนำแบรนด์อาหารเสริมกีฬาและสุขภาพชั้นนำจากยุโรปมาสู่ประเทศไทย เลือกดูแคตตาล็อกทั้งหมดด้านล่าง — สินค้าทั้งหมดจะพร้อมจำหน่ายในร้านค้าของเราในไทยเร็วๆ นี้!",
    productsCatalogSub: "แคตตาล็อกของเรา",
    productsCatalogTitle: "สินค้าทั้งหมด",
    productsCount: "สินค้า",
    productsNote: "สินค้าที่แสดงทั้งหมดมาจากแคตตาล็อกของเราในเนเธอร์แลนด์ และจะพร้อมจำหน่ายในร้านค้าประเทศไทยเร็วๆ นี้ ราคาอาจแตกต่างกัน",
    filterAll: "ทั้งหมด",
    // Pre-footer CTA
    prefooterVisitTitle: "เยี่ยมชมร้านของเรา",
    prefooterVisitText: "รับคำแนะนำส่วนตัวจากผู้เชี่ยวชาญด้านโภชนาการของเราในร้าน",
    prefooterVisitBtn: "ค้นหาร้าน",
    prefooterShopTitle: "ช็อปออนไลน์",
    prefooterShopText: "เลือกดูสินค้าทั้งหมดและสั่งซื้อจากทุกที่ในประเทศไทย",
    prefooterShopBtn: "ดูสินค้า",
    // Footer
    footerColTitle: "The Health House",
    footerShop: "สินค้า",
    footerBrands: "แบรนด์",
    footerAbout: "เกี่ยวกับเรา",
    footerFranchise: "แฟรนไชส์",
    footerServiceTitle: "บริการลูกค้า",
    footerContact: "ติดต่อเรา",
    footerJobs: "ร่วมงานกับเรา",
    footerFAQ: "คำถามที่พบบ่อย",
    footerReturns: "การคืนสินค้าและคืนเงิน",
    footerShipping: "ข้อมูลการจัดส่ง",
    footerLocTitle: "สาขาของเรา",
    footerLoc1: "กรุงเทพฯ สุขุมวิท",
    footerLoc2: "กรุงเทพฯ ทองหล่อ",
    footerLoc3: "เชียงใหม่",
    footerLoc4: "ภูเก็ต",
    footerNewsletterTitle: "ติดตามข่าวสาร",
    footerNewsletterText: "รับข่าวดีล สินค้าใหม่ และข้อเสนอพิเศษเมื่อสมัครสมาชิก",
    footerNewsletterPlaceholder: "กรอกอีเมล",
    footerNewsletterBtn: "สมัคร",
    footerPrivacy: "นโยบายความเป็นส่วนตัว",
    footerTerms: "ข้อกำหนดและเงื่อนไข",
    footerCookies: "คุกกี้",
  }
};

// ===== LANGUAGE SWITCHING =====
let currentLang = 'th';

function setLang(lang) {
  currentLang = lang;
  const t = translations[lang];

  // Update buttons
  document.querySelectorAll('.lang-switcher button').forEach(btn => {
    btn.classList.toggle('active', btn.id === 'btn-' + lang);
  });

  // Update text content
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) {
      el.textContent = t[key];
    }
  });

  // Update innerHTML (for elements with HTML like the hero title)
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const key = el.getAttribute('data-i18n-html');
    if (t[key] !== undefined) {
      el.innerHTML = t[key];
    }
  });

  // Update placeholders
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (t[key] !== undefined) {
      el.setAttribute('placeholder', t[key]);
    }
  });
}

// Initialize
document.addEventListener('DOMContentLoaded', () => {
  setLang('th');
});
